name: spacesignal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  tutorial_coach_mark: ^1.1.1
  simple_speed_dial: ^0.1.3
  google_fonts: ^2.1.0
  at_chat_flutter: ^3.0.3
  get: 4.3.8
  path_provider: ^2.0.2
  uuid: ^3.0.4
  flutter: 
    sdk: flutter
#  at_contact: ^3.0.3
  at_contacts_flutter: ^4.0.0
#  progress_dialog: ^1.2.4
  future_progress_dialog: ^0.2.0
  flutter_slidable: ^0.6.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  flutter_web_browser: ^0.15.0
  sliding_up_panel: ^2.0.0+1
  logger: ^1.1.0
  at_commons: ^3.0.2
  at_onboarding_flutter: ^3.1.4
#  at_client_mobile: ^3.1.4
#  at_client: ^3.0.8


dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client
      ref: trunk

  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client_mobile
      ref: trunk

  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: trunk

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/meee1.png"
  image_path_android: "assets/images/meee1.png"
  adaptive_icon_background: "assets/images/meee1.png"
  adaptive_icon_foreground: "assets/images/meee1.png"

flutter: 
  uses-material-design: true
  assets:
     - assets/images/
     - assets/images/logo_new.png