name: spacesignal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  tutorial_coach_mark: ^1.1.1
  simple_speed_dial: ^0.1.3
  google_fonts: ^2.1.0
  at_chat_flutter: ^3.0.1
  get: 4.3.8
  path_provider: ^2.0.2
  uuid: ^3.0.4
  flutter: 
    sdk: flutter
  at_contact: ^3.0.1
#  progress_dialog: ^1.2.4
  future_progress_dialog: ^0.2.0
  flutter_slidable: ^0.6.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  flutter_web_browser: ^0.15.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  at_common_flutter: ^2.0.2
  at_onboarding_flutter: ^3.0.2
  at_client_mobile: ^3.0.1
  at_client: ^3.0.0


flutter: 
  uses-material-design: true

  assets:
     - assets/images/